### ISSUE TITLE
Since the last update Nebula is completely broken

### ISSUE THREAD

**Issue by Superkooka** [dscalzi/Nebula#11]
With the bug I had previously (#9 and #10) I wanted to update Nebula and since no command works (I obviously rebuild / reclone)

Steps to reproduce the issue :
- First way with an old Nebla version
``git pull``

- Second way (fresh install)
``git clone https://github.com/dscalzi/Nebula.git``

Stack trace :

```
PS D:\Launcher\Helios\Nebula> node dist/index.js init root
 init root

Generate an empty standard file structure.

Options:
  --help  Show help                                                    [boolean]

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.resolve (path.js:136:9)
    at getRoot (D:\Launcher\Helios\Nebula\dist\index.js:20:19)
    at Object.handler (D:\Launcher\Helios\Nebula\dist\index.js:85:21)
    at Object.runCommand (D:\Launcher\Helios\Nebula\node_modules\yargs\lib\command.js:240:40)
    at Object.parseArgs [as _parseArgs] (D:\Launcher\Helios\Nebula\node_modules\yargs\yargs.js:1154:41)
    at Object.runCommand (D:\Launcher\Helios\Nebula\node_modules\yargs\lib\command.js:198:30)
    at Object.parseArgs [as _parseArgs] (D:\Launcher\Helios\Nebula\node_modules\yargs\yargs.js:1154:41)
    at Object.get [as argv] (D:\Launcher\Helios\Nebula\node_modules\yargs\yargs.js:1088:21)
    at Object.<anonymous> (D:\Launcher\Helios\Nebula\dist\index.js:268:5)
```

**Comment by dscalzi** [comment]
Cannot reproduce, works fine for me.. 

![image](https://user-images.githubusercontent.com/9703873/83538804-45cf9a00-a4c4-11ea-9235-ee9c75fe7dc1.png)

Try rebuilding
