### ISSUE TITLE
Failed to generate distribution with root Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by jakeau** [dscalzi/Nebula#16]
`[2020-07-29 01:50:02] [error] [Index]: Failed to generate distribution with root C:\Users\Jake\Downloads\Nebula-master\Nebula-master\serverstuff.
Error: spawn ENAMETOOLONG
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at Object.spawn (child_process.js:548:9)
    at C:\Users\Jake\Downloads\Nebula-master\Nebula-master\dist\util\java\JarExecutor.js:19:43
    at new Promise (<anonymous>)
    at ClaritasWrapper.executeJar (C:\Users\Jake\Downloads\Nebula-master\Nebula-master\dist\util\java\JarExecutor.js:18:16)
    at ClaritasWrapper.execute (C:\Users\Jake\Downloads\Nebula-master\Nebula-master\dist\util\java\ClaritasWrapper.js:33:22)
    at ForgeModStructure17.invokeClaritas (C:\Users\Jake\Downloads\Nebula-master\Nebula-master\dist\model\struct\model\module\module.struct.js:102:58)
    at ForgeModStructure17._doModuleRetrieval (C:\Users\Jake\Downloads\Nebula-master\Nebula-master\dist\model\struct\model\module\module.struct.js:118:24)
    at ForgeModStructure17.getSpecModel (C:\Users\Jake\Downloads\Nebula-master\Nebula-master\dist\model\struct\model\module\toggleablemodule.struct.js:29:46)
    at async ServerStructure._doSeverRetrieval (C:\Users\Jake\Downloads\Nebula-master\Nebula-master\dist\model\struct\model\server.struct.js:91:45)`

Caused when the total name of all the strings (name of mods in required folder) is larger than a specific value.

**Comment by dscalzi** [comment]
@jakeau Can you pull the latest changes and verify that the problem is fixed?
