### ISSUE TITLE
Clartias Crashes

### ISSUE THREAD

**Issue by lilRufi** [dscalzi/Nebula#36]
```
[2021-09-23 19:38:29] [error] [Claritas]: Exception in thread "main"
[2021-09-23 19:38:29] [error] [Claritas]: java.lang.NullPointerException
        at org.objectweb.asm.Type.getObjectType(Type.java:253)
        at com.dscalzi.claritas.asm.ClaritasClassVisitor.visit(ClaritasClassVisitor.java:53)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at com.dscalzi.claritas.resolver.MetadataResolver.getClaritasClassVisitor(MetadataResolver.java:51)
        at com.dscalzi.claritas.resolver.library.forge.ForgeMetadataResolver_1_13.resolveMetadata(ForgeMetadataResolver_1_13.java:48)
        at com.dscalzi.claritas.discovery.LibraryAnalyzer.analyze(LibraryAnalyzer.java:87)
        at com.dscalzi.claritas.Main.main(Main.java:91)
[2021-09-23 19:38:29] [info] [Claritas]: Exited with code 1
[2021-09-23 19:38:29] [error] [Claritas]: Claritas finished with non-zero exit code,  1
[2021-09-23 19:38:29] [error] [ForgeModStructure (1.13)]: Failed to process Claritas result!
[2021-09-23 19:38:29] [error] [ForgeModStructure (1.13)]: Claritas failed to yield metadata for ForgeMod AdvancedCompas-forge-1.16.5-1.2.1.jar!
[2021-09-23 19:38:29] [error] [ForgeModStructure (1.13)]: Is this mod malformated or does Claritas need an update?
[2021-09-23 19:38:29] [debug] [ForgeModStructure (1.13)]: [
  'Manifest-Version: 1.0\r',
  'Implementation-Title: AdvancedCompas(Forge-1.16.5)\r',
  'Implementation-Version: 1.2.1\r',
  'Specification-Vendor: DmitryLovin\r',
  'Specification-Title: Advanced Compass\r',
  'Implementation-Timestamp: 2021-06-13T12:56:45+1000\r',
  'Specification-Version: 1.2.1\r',
  'Implementation-Vendor: DmitryLovin\r',
  '\r',
  ''
]
[2021-09-23 19:38:29] [debug] [ForgeModStructure (1.13)]: ForgeMod AdvancedCompas-forge-1.16.5-1.2.1.jar contains a version wildcard, inferring 1.2.1 
[2021-09-23 19:38:29] [error] [Index]: Failed to generate distribution with root C:\Users\Rauf\Nebula\Nebula\ROOT\launcher.
TypeError: Cannot read property 'C:\Users\Rauf\Nebula\Nebula\ROOT\launcher\servers\Gama-1.16.5\forgemods\required\AdvancedCompas-forge-1.16.5-1.2.1.jar' of undefined
    at ForgeModStructure113.getClaritasGroup (C:\Users\Rauf\Nebula\Nebula\dist\structure\spec_model\module\Module.struct.js:55:35)
    at ForgeModStructure113.getModuleId (C:\Users\Rauf\Nebula\Nebula\dist\structure\spec_model\module\forgemod\ForgeMod113.struct.js:29:50)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ForgeModStructure113.parseModule (C:\Users\Rauf\Nebula\Nebula\dist\structure\spec_model\module\Module.struct.js:78:17)
    at async ForgeModStructure113._doModuleRetrieval (C:\Users\Rauf\Nebula\Nebula\dist\structure\spec_model\module\Module.struct.js:138:29)
    at async ForgeModStructure113.getSpecModel (C:\Users\Rauf\Nebula\Nebula\dist\structure\spec_model\module\ToggleableModule.struct.js:29:35)        
    at async ForgeModStructure113.getSpecModel (C:\Users\Rauf\Nebula\Nebula\dist\structure\spec_model\module\ForgeMod.struct.js:16:17)
    at async ServerStructure._doSeverRetrieval (C:\Users\Rauf\Nebula\Nebula\dist\structure\spec_model\Server.struct.js:95:45)
    at async ServerStructure.getSpecModel (C:\Users\Rauf\Nebula\Nebula\dist\structure\spec_model\Server.struct.js:28:35)
    at async DistributionStructure.getSpecModel (C:\Users\Rauf\Nebula\Nebula\dist\structure\spec_model\Distribution.struct.js:39:22)
    
    

```

**Comment by dscalzi** [comment]
Unable to reproduce. I ran 1.16.5 with the same mod and it worked fine. I tried both Java 8 and Java 16.

**Comment by dscalzi** [comment]
Same bug as https://github.com/dscalzi/Nebula/issues/35, resolved.
