### ISSUE TITLE
Claritas Out of Bounds Exception

### ISSUE THREAD

**Issue by BuiltByBrandon** [dscalzi/Nebula#41]
```
[2022-01-20 15:50:53] [error] [Claritas]: Exception in thread "main"
[2022-01-20 15:50:53] [error] [Claritas]: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at com.dscalzi.claritas.util.DataUtil.getPackage(DataUtil.java:60)
        at com.dscalzi.claritas.resolver.library.forge.ForgeMetadataResolver_1_13.lambda$resolveMetadata$1(ForgeMetadataResolver_1_13.java:59)
        at java.util.Optional.map(Optional.java:215)
        at com.dscalzi.claritas.resolver.library.forge.ForgeMetadataResolver_1_13.resolveMetadata(ForgeMetadataResolver_1_13.java:52)
        at com.dscalzi.claritas.discovery.LibraryAnalyzer.analyze(LibraryAnalyzer.java:87)
        at com.dscalzi.claritas.Main.main(Main.java:91)
[2022-01-20 15:50:53] [info] [Claritas]: Exited with code 1
[2022-01-20 15:50:53] [error] [Claritas]: Claritas finished with non-zero exit code,  1
[2022-01-20 15:50:53] [error] [ForgeModStructure (1.13)]: Failed to process Claritas result!
[2022-01-20 15:50:53] [error] [ForgeModStructure (1.13)]: Claritas failed to yield metadata for ForgeMod Abundance-1.16.5.jar!
[2022-01-20 15:50:53] [error] [ForgeModStructure (1.13)]: Is this mod malformated or does Claritas need an update?
[2022-01-20 15:50:53] [debug] [ForgeModStructure (1.13)]: ForgeMod Abundance-1.16.5.jar contains a version wildcard, inferring 1.16.5-1.0.5
[2022-01-20 15:50:53] [error] [Index]: Failed to generate distribution with root C:\Users\guzma\Documents\Studz\StudzDistro\EssenceCubed.
TypeError: Cannot read properties of undefined (reading 'C:\Users\guzma\Documents\Studz\StudzDistro\EssenceCubed\servers\EssenceCubed-1.16.5\forgemods\required\Abundance-1.16.5.jar')
    at ForgeModStructure113.getClaritasGroup (C:\Users\guzma\Documents\Studz\StudzNeb\Nebula\dist\structure\spec_model\module\Module.struct.js:55:35)
    at ForgeModStructure113.getModuleId (C:\Users\guzma\Documents\Studz\StudzNeb\Nebula\dist\structure\spec_model\module\forgemod\ForgeMod113.struct.js:29:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ForgeModStructure113.parseModule (C:\Users\guzma\Documents\Studz\StudzNeb\Nebula\dist\structure\spec_model\module\Module.struct.js:78:17)
    at async ForgeModStructure113._doModuleRetrieval (C:\Users\guzma\Documents\Studz\StudzNeb\Nebula\dist\structure\spec_model\module\Module.struct.js:138:29)
    at async ForgeModStructure113.getSpecModel (C:\Users\guzma\Documents\Studz\StudzNeb\Nebula\dist\structure\spec_model\module\ToggleableModule.struct.js:29:35)
    at async ForgeModStructure113.getSpecModel (C:\Users\guzma\Documents\Studz\StudzNeb\Nebula\dist\structure\spec_model\module\ForgeMod.struct.js:16:17)
    at async ServerStructure._doSeverRetrieval (C:\Users\guzma\Documents\Studz\StudzNeb\Nebula\dist\structure\spec_model\Server.struct.js:96:45)
    at async ServerStructure.getSpecModel (C:\Users\guzma\Documents\Studz\StudzNeb\Nebula\dist\structure\spec_model\Server.struct.js:28:35)
```

This error occurs with _Abundance_ and several other mods such as _Large Ore Deposits_

**Comment by dscalzi** [comment]
Can you send me the full of your forgemods folder? I don't think Abundance is the problem.

**Comment by BuiltByBrandon** [comment]
> Can you send me a full zip of your forgemods folder? I don't think Abundance is the problem.

Here you go , [https://github.com/BuiltByBrandon/EssenceCubed-1.16.5/releases/download/debug/forgemods.zip](https://github.com/BuiltByBrandon/EssenceCubed-1.16.5/releases/download/debug/forgemods.zip)

**Comment by dscalzi** [comment]
Thanks, I will take a look today

**Comment by dscalzi** [comment]
The problem is with abyg-1.2-forge.jar providing their Main class in the default package. I will be pushing a fix for Claritas and updating the jar in Nebula. Mods that do this will not be resolvable and nebula will assign a generated identifier.

**Comment by dscalzi** [comment]
Should be working now, let me know. Thanks for the report.
