### ISSUE TITLE
Can't generate distro with forge "1.12.2 - 14.23.5.2859"

### ISSUE THREAD

**Issue by Banane480** [dscalzi/Nebula#47]
When I try to generate I have this error : 

```
[2022-09-18 15:29:40] [error] [Index]: Failed to generate distribution with root C:\Users\aidan\Desktop\vaniria\root.
Error: Cannot compare mismatched versions.
    at Function.versionGte (C:\Users\aidan\Desktop\vaniria\Nebula-master\dist\util\versionutil.js:59:19)
    at ForgeGradle2Adapter.checkSecurity (C:\Users\aidan\Desktop\vaniria\Nebula-master\dist\resolver\forge\forge.resolver.js:48:53)
    at new ForgeResolver (C:\Users\aidan\Desktop\vaniria\Nebula-master\dist\resolver\forge\forge.resolver.js:24:14)
    at new ForgeGradle2Adapter (C:\Users\aidan\Desktop\vaniria\Nebula-master\dist\resolver\forge\adapter\ForgeGradle2.resolver.js:16:9)
    at Function.getForgeResolver (C:\Users\aidan\Desktop\vaniria\Nebula-master\dist\util\VersionSegmentedRegistry.js:12:24)
    at ServerStructure._doSeverRetrieval (C:\Users\aidan\Desktop\vaniria\Nebula-master\dist\structure\spec_model\Server.struct.js:85:95)
    at async ServerStructure.getSpecModel (C:\Users\aidan\Desktop\vaniria\Nebula-master\dist\structure\spec_model\Server.struct.js:27:35)
    at async DistributionStructure.getSpecModel (C:\Users\aidan\Desktop\vaniria\Nebula-master\dist\structure\spec_model\Distribution.struct.js:39:22)
    at async Object.handler (C:\Users\aidan\Desktop\vaniria\Nebula-master\dist\index.js:217:28)
```

If you know what it meens please help !!

**Comment by Banane480** [comment]
PS: I use forge **1.12.2 - 14.23.5.2859**

**Comment by dscalzi** [comment]
I just tried myself and am not having this issue. What steps did you take?
