### ISSUE TITLE
Claritas error

### ISSUE THREAD

**Issue by VozDeOuro** [dscalzi/Nebula#48]
trying to do at 1.18.2 minecraft version 
the claritas update on other issues seams to not work 
running on branch feature/1.17
 
`[2022-09-30 15:18:58] [info] [Claritas]: 15:18:58.939 [main] DEBUG com.dscalzi.claritas.Main - OUTPUT     = C:\Users\lucas\Desktop\jarvis\launchers\Nebula-master\root\servers\LCSV-1.18.2\claritasWork\claritasOutput.json
[2022-09-30 15:18:59] [error] [Claritas]: Exception in thread "main"
[2022-09-30 15:18:59] [error] [Claritas]: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:262)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)
        at com.dscalzi.claritas.resolver.MetadataResolver.getClaritasClassVisitor(MetadataResolver.java:50)
        at com.dscalzi.claritas.resolver.library.forge.ForgeMetadataResolver_1_13.resolveMetadata(ForgeMetadataResolver_1_13.java:48)
        at com.dscalzi.claritas.discovery.LibraryAnalyzer.analyze(LibraryAnalyzer.java:87)
        at com.dscalzi.claritas.Main.main(Main.java:91)
[2022-09-30 15:18:59] [info] [Claritas]: Exited with code 1
[2022-09-30 15:18:59] [error] [Claritas]: Claritas finished with non-zero exit code,  1
[2022-09-30 15:18:59] [error] [ForgeModStructure (1.13)]: Failed to process Claritas result!
[2022-09-30 15:18:59] [error] [ForgeModStructure (1.13)]: Claritas failed to yield metadata for ForgeMod AE2WTLib-11.1.5.jar!
[2022-09-30 15:18:59] [error] [ForgeModStructure (1.13)]: Is this mod malformated or does Claritas need an update?
[2022-09-30 15:18:59] [error] [Index]: Failed to generate distribution with root C:\Users\lucas\Desktop\jarvis\launchers\Nebula-master\root.
TypeError: Cannot read properties of undefined (reading 'C:\Users\lucas\Desktop\jarvis\launchers\Nebula-master\root\servers\LCSV-1.18.2\forgemods\required\AE2WTLib-11.1.5.jar')
    at ForgeModStructure113.getClaritasGroup (C:\Users\lucas\Desktop\jarvis\launchers\Nebula-master\dist\structure\spec_model\module\Module.struct.js:55:35)
    at ForgeModStructure113.getModuleId (C:\Users\lucas\Desktop\jarvis\launchers\Nebula-master\dist\structure\spec_model\module\forgemod\ForgeMod113.struct.js:29:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ForgeModStructure113.parseModule (C:\Users\lucas\Desktop\jarvis\launchers\Nebula-master\dist\structure\spec_model\module\Module.struct.js:78:17)
    at async ForgeModStructure113._doModuleRetrieval (C:\Users\lucas\Desktop\jarvis\launchers\Nebula-master\dist\structure\spec_model\module\Module.struct.js:138:29)
    at async ForgeModStructure113.getSpecModel (C:\Users\lucas\Desktop\jarvis\launchers\Nebula-master\dist\structure\spec_model\module\ToggleableModule.struct.js:29:35)
    at async ForgeModStructure113.getSpecModel (C:\Users\lucas\Desktop\jarvis\launchers\Nebula-master\dist\structure\spec_model\module\ForgeMod.struct.js:16:17)
    at async ServerStructure._doSeverRetrieval (C:\Users\lucas\Desktop\jarvis\launchers\Nebula-master\dist\structure\spec_model\Server.struct.js:90:45)
    at async ServerStructure.getSpecModel (C:\Users\lucas\Desktop\jarvis\launchers\Nebula-master\dist\structure\spec_model\Server.struct.js:27:35)
    at async DistributionStructure.getSpecModel (C:\Users\lucas\Desktop\jarvis\launchers\Nebula-master\dist\structure\spec_model\Distribution.struct.js:39:22)`

**Comment by VozDeOuro** [comment]
did more tests and seems to be a specific mod that is causing that error 

this one 
https://www.curseforge.com/minecraft/mc-mods/terralith

i dont know why maybe because the mod is treated like a datapack ? 
but can you implement a fix about it ?

**Comment by Raft08** [comment]
I have the same error with the mod AE2-Things-1.0.5.jar

**Comment by dscalzi** [comment]
I'll check

**Comment by dscalzi** [comment]
> I have the same error with the mod AE2-Things-1.0.5.jar

@Raft08 The file worked fine for me.

**Comment by dscalzi** [comment]
Terralith also worked @VozDeOuro, please try on the latest master code.
