### ISSUE TITLE
error help.....

### ISSUE THREAD

**Issue by LeePC** [dscalzi/Nebula#64]
[2023-09-18 13시 23분 7초] [error] [Claritas]: Exception in thread "main"
[2023-09-18 13시 23분 7초] [error] [Claritas]: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:262)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)
        at com.dscalzi.claritas.resolver.MetadataResolver.getClaritasClassVisitor(MetadataResolver.java:50)
        at com.dscalzi.claritas.resolver.library.forge.ForgeMetadataResolver_1_13.resolveMetadata(ForgeMetadataResolver_1_13.java:48)
        at com.dscalzi.claritas.discovery.LibraryAnalyzer.analyze(LibraryAnalyzer.java:73)
        at com.dscalzi.claritas.Main.main(Main.java:91)
[2023-09-18 13시 23분 7초] [info] [Claritas]: Exited with code 1
[2023-09-18 13시 23분 7초] [error] [Claritas]: Claritas finished with non-zero exit code,  1
[2023-09-18 13시 23분 8초] [error] [ForgeModStructure (1.13)]: Failed to process Claritas result!
[2023-09-18 13시 23분 8초] [error] [ForgeModStructure (1.13)]: Claritas failed to yield metadata for ForgeMod 1.18.2netherskeletons4.8.jar!
[2023-09-18 13시 23분 8초] [error] [ForgeModStructure (1.13)]: Is this mod malformated or does Claritas need an update?
[2023-09-18 13시 23분 8초] [error] [Index]: Failed to generate distribution with root C:\Users\LEEPC\Documents\1\StreamerServer.
TypeError: Cannot read properties of undefined (reading 'C:\Users\LEEPC\Documents\1\StreamerServer\servers\JuniServer1-1.18.2\forgemods\required\1.18.2netherskeletons4.8.jar')
    at ForgeModStructure113.getClaritasGroup (file:///C:/Users/LEEPC/Documents/1/Nebula/Nebula/dist/structure/spec_model/module/Module.struct.js:55:35)
    at ForgeModStructure113.getModuleId (file:///C:/Users/LEEPC/Documents/1/Nebula/Nebula/dist/structure/spec_model/module/forgemod/ForgeMod113.struct.js:24:50)        
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ForgeModStructure113.parseModule (file:///C:/Users/LEEPC/Documents/1/Nebula/Nebula/dist/structure/spec_model/module/Module.struct.js:78:17)
    at async ForgeModStructure113._doModuleRetrieval (file:///C:/Users/LEEPC/Documents/1/Nebula/Nebula/dist/structure/spec_model/module/Module.struct.js:138:29)        
    at async ForgeModStructure113.getSpecModel (file:///C:/Users/LEEPC/Documents/1/Nebula/Nebula/dist/structure/spec_model/module/ToggleableModule.struct.js:27:35)     
    at async ForgeModStructure113.getSpecModel (file:///C:/Users/LEEPC/Documents/1/Nebula/Nebula/dist/structure/spec_model/module/ForgeMod.struct.js:13:17)
    at async ServerStructure._doSeverRetrieval (file:///C:/Users/LEEPC/Documents/1/Nebula/Nebula/dist/structure/spec_model/Server.struct.js:111:45)
    at async ServerStructure.getSpecModel (file:///C:/Users/LEEPC/Documents/1/Nebula/Nebula/dist/structure/spec_model/Server.struct.js:28:35)
    at async DistributionStructure.getSpecModel (file:///C:/Users/LEEPC/Documents/1/Nebula/Nebula/dist/structure/spec_model/Distribution.struct.js:41:22)

One specific mods causes a crash

**Comment by dscalzi** [comment]
That mod worked fine for me, how many mods do you have?

**Comment by LeePC** [comment]
208 mods

**Comment by foxypiratecove37350** [comment]
> 208 mods

Bro, this isn't made for too mods, 208 is just an enormous number of mods.
