### ISSUE TITLE
Does not work on the latest Minecraft Forge 1.12.2 versions (14.23.5.2854) version.json

### ISSUE THREAD

**Issue by MichelBaie** [dscalzi/Nebula#8]
I recently wanted to create a .json distribution with the latest version 1.12.2 (14.23.5.2854).
However, since they recently changed the way the .jar is made, there is no longer the .json version.
So he gives me this mistake:
`Downloading https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar..
Completed download of https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar.
Beginning processing of Forge v14.23.5.2854 (Minecraft 1.12.2)
Failed to generate distribution with root F:\Profil\Documents\GitHub\Nebula. Error: Failed to find version.json in forge universal jar.
    at Forge17Adapter.getForgeByVersion (F:\Profil\Documents\GitHub\Nebula\dist\resolver\forge\adapter\forge17.resolver.js:54:19)
    at async ServerStructure._doSeverRetrieval (F:\Profil\Documents\GitHub\Nebula\dist\model\struct\model\server.struct.js:80:43)
    at async ServerStructure.getSpecModel (F:\Profil\Documents\GitHub\Nebula\dist\model\struct\model\server.struct.js:19:35)
    at async DistributionStructure.getSpecModel (F:\Profil\Documents\GitHub\Nebula\dist\model\struct\model\distribution.struct.js:20:22)
    at async Object.handler (F:\Profil\Documents\GitHub\Nebula\dist\index.js:171:28)`
Do you have a solution? Or a patch?

**Comment by dscalzi** [comment]
Investigating

**Comment by dscalzi** [comment]
Forge changed the format for the last three 1.12.2 builds. Special handling will have to be added..

**Comment by MichelBaie** [comment]
1.12.2 now is actually not working with all versions because they remove the sources of the latest versions wich has the version.json

**Comment by dscalzi** [comment]
I'm pretty sure they ported 1.12.2 to ForgeGradle 3, hence why it has a 1.13-style installer system now. I know how it works I just need some time to refactor the code a bit. I can hack in a fix but that's not ideal.

**Comment by MichelBaie** [comment]
They removed the sources of this build from they servers.
Si i've this 404 error :
`Downloading https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar..
Completed download of https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar.
Beginning processing of Forge v14.23.5.2854 (Minecraft 1.12.2)
Failed to generate distribution with root F:\Profil\Documents\GitHub\Nebula. Error: Failed to find version.json in forge universal jar.
    at Forge17Adapter.getForgeByVersion (F:\Profil\Documents\GitHub\Nebula\dist\resolver\forge\adapter\forge17.resolver.js:54:19)
    at async ServerStructure._doSeverRetrieval (F:\Profil\Documents\GitHub\Nebula\dist\model\struct\model\server.struct.js:80:43)
    at async ServerStructure.getSpecModel (F:\Profil\Documents\GitHub\Nebula\dist\model\struct\model\server.struct.js:19:35)
    at async DistributionStructure.getSpecModel (F:\Profil\Documents\GitHub\Nebula\dist\model\struct\model\distribution.struct.js:20:22)
    at async Object.handler (F:\Profil\Documents\GitHub\Nebula\dist\index.js:171:28)`

**Comment by dscalzi** [comment]
That's not the issue. Don't worry I'll fix it tomorrow

**Comment by dscalzi** [comment]
Downloads for the old forge universal jars are fixed. Still working on the fix for the new builds.

**Comment by dscalzi** [comment]
Support has been added to Nebula. I will close this issue once the patch is in Helios and it's verified to be working as expected.

**Comment by dscalzi** [comment]
Patched in Helios. Please sync your repos and verify that everything is working with your distribution. If anything was overlooked or broken please let me know!
